[manifest]
version = "1.0.0"
priority = 0

# generate_card_ui()
# remove extra_slots_used tooltip from gigantic cards
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
match_indent = true
position = "at"
pattern = "if not hide_desc and card and card.ability and (card.ability.extra_slots_used or 0) ~= 0 then"
payload = '''
local minus_gigantic = card and card.ability and card.ability.srdx_gigantic and 1 or 0
if not hide_desc and card and card.ability and ((card.ability.extra_slots_used or 0) - minus_gigantic) ~= 0 then
'''
